Repository Ucommercenet/Ucommerce.Sitefinity.UI, pull requests merged in 2021-06, with the labels that each got.

#70 Fix selectedVariants bug that's it's not set on product load
  Ucommerce.Sitefinity.UI/assets/src/js/widgets/products.js
Labels: bug, triaged

#62 Release/3.4.0
  README.md
  Ucommerce.Sitefinity.UI/App_Data/Sitefinity/GlobalResources/Admin.da.resx
  Ucommerce.Sitefinity.UI/App_Data/Sitefinity/GlobalResources/Admin.de.resx
  Ucommerce.Sitefinity.UI/App_Data/Sitefinity/GlobalResources/Admin.resx
  Ucommerce.Sitefinity.UI/App_Data/Sitefinity/GlobalResources/Admin.sv.resx
  Ucommerce.Sitefinity.UI/Mvc/Model/FacetsFilterModel.cs
  Ucommerce.Sitefinity.UI/Properties/AssemblyInfo.cs
  Ucommerce.Sitefinity.UI/UCommerce/Apps/Braintree/BraintreePaymentForm.htm
  Ucommerce.Sitefinity.UI/UCommerce/Apps/Ucommerce.Search.ElasticSearch.disabled/Configuration/Search.ElasticSearch.config
  Ucommerce.Sitefinity.UI/UCommerce/Apps/Ucommerce.Search.Lucene/Configuration/Search.Lucene.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Components.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Core.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Indexes/CategoriesIndex.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Indexes/DefaultMetaIndex.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Indexes/PriceGroupsIndex.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Indexes/ProductCatalogGroupsIndex.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Indexes/ProductCatalogsIndex.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Indexes/ProductsIndex.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Search.config
  Ucommerce.Sitefinity.UI/UCommerce/Configuration/Settings/Settings.config
  Ucommerce.Sitefinity.UI/UCommerce/Pipelines/Admin/Catalogs.ProductCatalogGroup.Delete.config
  Ucommerce.Sitefinity.UI/UCommerce/Settings/Search/IndexFromScratch.ascx
  Ucommerce.Sitefinity.UI/UCommerce/Vue/catalogs.html
  Ucommerce.Sitefinity.UI/UCommerce/Vue/css/catalogs.0a485662.css
  Ucommerce.Sitefinity.UI/UCommerce/Vue/css/chunk-vendors.1331fd25.css
  Ucommerce.Sitefinity.UI/UCommerce/Vue/css/dashboard.4c5a7ccb.css
  Ucommerce.Sitefinity.UI/UCommerce/Vue/dashboard.html
  Ucommerce.Sitefinity.UI/UCommerce/Vue/favicon-16x16.png
  Ucommerce.Sitefinity.UI/UCommerce/Vue/favicon-192x192.png
  Ucommerce.Sitefinity.UI/UCommerce/Vue/favicon-32x32.png
  Ucommerce.Sitefinity.UI/UCommerce/Vue/favicon-96x96.png
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/catalogs.fbe8e7f3.js
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/catalogs.fbe8e7f3.js.map
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/chunk-common.44808e17.js
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/chunk-common.44808e17.js.map
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/chunk-vendors.d2786169.js
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/chunk-vendors.d2786169.js.map
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/dashboard.2bcf4d23.js
  Ucommerce.Sitefinity.UI/UCommerce/Vue/js/dashboard.2bcf4d23.js.map
  Ucommerce.Sitefinity.UI/UCommerce/install/ClientDependency.config
  Ucommerce.Sitefinity.UI/UCommerce/install/uCommerceDB.215.sql
  Ucommerce.Sitefinity.UI/UCommerce/install/uCommerceDB.216.sql
  Ucommerce.Sitefinity.UI/UCommerce/shell/App/routes.js
  Ucommerce.Sitefinity.UI/UCommerce/shell/CatalogsWrapper.ascx
  Ucommerce.Sitefinity.UI/UCommerce/shell/ProductsWrapper.ascx
  Ucommerce.Sitefinity.UI/UCommerce/shell/StoresWrapper.ascx
  Ucommerce.Sitefinity.UI/Ucommerce.Sitefinity.UI.csproj
  Ucommerce.Sitefinity.UI/Ucommerce.Sitefinity.UI.nuspec
  Ucommerce.Sitefinity.UI/assets/src/js/widgets/address.js
  Ucommerce.Sitefinity.UI/packages.config
Labels: triaged

#63 BugFix: Remove hardcoded title from product image
  ResourcePackages/Bootstrap4/MVC/Views/Products/List.Index.cshtml
Labels: bug

#69 Add Related Products to the ProductDetailViewModel
  Ucommerce.Sitefinity.UI/Mvc/Controllers/ProductsController.cs
  Ucommerce.Sitefinity.UI/Mvc/Model/ProductModel.cs
  Ucommerce.Sitefinity.UI/Mvc/ViewModels/ProductDetailViewModel.cs
Labels: bug, triaged
